openapi: 3.0.0
info:
  title: Image API
  version: 1.0.0
  description: API for uploading and retrieving images
servers:
  - url: http://localhost:3000/api
    description: Local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /upload:
    post:
      summary: Upload an image
      tags:
        - Images
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The image file to upload
      responses:
        '200':
          description: Image uploaded successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /images:
    get:
      summary: Retrieve all images
      tags:
        - Images
      responses:
        '200':
          description: A list of images
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /images/{imageId}:
    get:
      summary: Retrieve a single image by ID
      tags:
        - Images
      parameters:
        - name: imageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An image
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
        '404':
          description: Image not found
      security:
        - bearerAuth: []
